name: Simple CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Install and test backend
        run: |
          cd backend
          npm install
          npm run test
